# Generated by Django 3.1 on 2020-11-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookswap', '0008_auto_20201121_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='img',
            field=models.ImageField(default='static/bookswap/book.svg', upload_to='images/'),
        ),
    ]
