# Generated by Django 3.1 on 2020-11-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookswap', '0006_auto_20201120_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='img',
            field=models.ImageField(default='static/bookswap/book.svg', upload_to='static/'),
        ),
    ]
