# Generated by Django 3.1.3 on 2020-11-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookswap', '0008_auto_20201121_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='img',
            field=models.ImageField(default='static/bookswap/book.svg', null=True, upload_to='images/'),
        ),
    ]
