# Generated by Django 3.1 on 2020-11-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookswap', '0015_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='check_req',
            field=models.IntegerField(default=0, max_length=4),
        ),
    ]
