# Generated by Django 3.1 on 2020-11-28 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookswap', '0017_listing_duplicate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Listing_duplicate',
        ),
    ]
